### ISSUE TITLE
Explain how fees % is computed for add/remove_liquidity in stable_swap (Curve). 

### ISSUE THREAD

**Issue by vivekvpandya** [Dapp-Learning-DAO/Dapp-Learning#667]
Basically how following is derived mathematically.
```
 19         fee: uint256 = self.fee * N_COINS / (4 * (N_COINS - 1))                                                                                                                                                                          
```

**Comment by maroonstar** [comment]
`N_COINS / (4 * (N_COINS - 1))`

I think this part is an adjustment coefficient that depends on N. 

More categories of assets in the pool, the fees charged on the imbalanced part will be lower, but not less than 1/4 of the normal fees.

## Why do we need this coefficient?

Because when we add or remove liquidity imbalanced, the imbalanced part is actually treated as a half (or less) trade.
For example, I could add only USDC and then remove only DAI, and the two liquidity operations would make up a complete trade.

Since it is not a complete trade, you need to multiply the rate by a coefficient.

## how it works

Let's say N is equal to 2, so this coefficient is equal to 1/2. Since there are only two assets in the pool, an imbalanced addition or removal is exactly half a trade.

When N > 2, the impact of unbalanced liquidity operations on prices will be spread across more assets. It's easy to see that as N gets bigger, the coefficient gets closer and closer to 1/4.

You may join our discord channel for more discussion.

https://discord.gg/cRYNYXqPeR
